import type { SheetSchema } from "./types";

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
] as const;

/** Canonical source-type list, matching the ETL validator's vocabulary. */
const SOURCE_TYPES = [
  "Annual Report",
  "Company Website",
  "Forbes",
  "Fortune",
  "Others",
  "Reuters",
] as const;

const HUB_STRUCTURES = [
  "Standalone",
  "Hub-and-Spoke",
  "Hub-dominant",
  "Distributed",
  "Single-city",
  "No centres",
] as const;

/**
 * `accounts` is one row per company. Field order below is the column order in
 * the sheet, A onwards: the repo maps fields to columns by position.
 */
export const ACCOUNTS_SCHEMA: SheetSchema = {
  id: "accounts",
  sheetName: "accounts",
  label: "Accounts",
  idHeader: "uuid",
  idPrefix: "BR",
  titleHeader: "account_global_legal_name",
  // One row is one company, so the legal name really must be unique.
  titleUnique: true,
  subtitleHeaders: ["account_hq_city", "account_hq_country"],
  archiveSheetName: "accounts_archive",
  groups: [
    "Identity",
    "Company",
    "HQ Location",
    "Web & Profile",
    "Classification",
    "Revenue",
    "Employees",
    "India Footprint",
    "Notes",
  ],
  fields: [
    {
      key: "uuid",
      header: "uuid",
      label: "UUID",
      kind: "readonly",
      group: "Identity",
      inTable: true,
      help: "Assigned automatically on create. Never changes.",
    },
    {
      key: "lastUpdateDate",
      header: "account_last_update_date",
      label: "Last Update Date",
      kind: "date",
      required: true,
      group: "Identity",
      inTable: true,
      help: "Stored as d-MMMM-yyyy to match the existing sheet.",
    },
    {
      key: "nasscomStatus",
      header: "account_nasscom_status",
      label: "Nasscom Status",
      kind: "select",
      required: true,
      options: ["Yes", "No"],
      group: "Identity",
    },
    {
      key: "nasscomMemberStatus",
      header: "account_nasscom_member_status",
      label: "Nasscom Member Status",
      kind: "select",
      required: true,
      options: ["Yes", "No"],
      group: "Identity",
    },
    {
      key: "dataCoverage",
      header: "account_data_coverage",
      label: "Data Coverage",
      kind: "select",
      required: true,
      options: ["L1", "L2", "L3"],
      group: "Identity",
    },
    {
      key: "source",
      header: "account_source",
      label: "Source",
      kind: "select",
      required: true,
      options: ["Bamboo Reports"],
      group: "Identity",
    },
    {
      key: "accountType",
      header: "account_type",
      label: "Account Type",
      kind: "select",
      required: true,
      options: ["Global Enterprise", "Indian Enterprise"],
      group: "Identity",
    },

    {
      key: "accountName",
      header: "account_global_legal_name",
      label: "Account Global Legal Name",
      kind: "text",
      required: true,
      noUrl: true,
      group: "Company",
      inTable: true,
      maxLength: 150,
      help: "Must be unique across accounts.",
    },
    {
      key: "aboutCompany",
      header: "account_about",
      label: "About Company",
      kind: "longtext",
      required: true,
      noUrl: true,
      group: "Company",
      maxLength: 2000,
    },

    {
      key: "hqAddress",
      header: "account_hq_address",
      label: "HQ Address",
      kind: "longtext",
      required: true,
      noUrl: true,
      group: "HQ Location",
      maxLength: 250,
    },
    { key: "hqCity", header: "account_hq_city", label: "HQ City", kind: "combo", required: true, noUrl: true, group: "HQ Location", inTable: true },
    { key: "hqState", header: "account_hq_state", label: "HQ State", kind: "combo", required: true, noUrl: true, group: "HQ Location" },
    { key: "hqZip", header: "account_hq_zip_code", label: "HQ ZIP Code", kind: "text", noUrl: true, group: "HQ Location" },
    { key: "hqCountry", header: "account_hq_country", label: "HQ Country", kind: "combo", required: true, noUrl: true, group: "HQ Location", inTable: true },
    {
      key: "hqRegion",
      header: "account_hq_region",
      label: "HQ Region",
      kind: "select",
      required: true,
      options: ["North America", "Europe", "APAC", "MEA", "LATAM"],
      group: "HQ Location",
    },

    { key: "hqBoardline", header: "account_hq_boardline", label: "HQ Boardline", kind: "text", format: "digits", noUrl: true, group: "Web & Profile", help: "Main switchboard number." },
    { key: "hqWebsite", header: "account_hq_website", label: "HQ Website", kind: "url", required: true, group: "Web & Profile", inTable: true },
    { key: "linkedin", header: "account_hq_linkedin_link", label: "LinkedIn Link", kind: "url", format: "linkedin", group: "Web & Profile" },
    {
      key: "hqOfferings",
      header: "account_hq_key_offerings",
      label: "HQ Key Offerings",
      kind: "longtext",
      required: true,
      noUrl: true,
      group: "Web & Profile",
      maxLength: 600,
      help: "One offering per line.",
    },
    { key: "offeringSourceLink", header: "account_key_offerings_source_link", label: "Key Offerings Source Link", kind: "url", group: "Web & Profile" },

    {
      key: "hqSubIndustry",
      header: "account_hq_sub_industry",
      label: "HQ Sub Industry",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Classification",
      optionSource: { sheetName: "irxdx", header: "Sub Industry" },
      help: "Choose a Sub Industry from irxdx. The related classification fields fill automatically.",
    },
    {
      key: "hqIndustry",
      header: "account_hq_industry",
      label: "HQ Industry",
      kind: "readonly",
      computed: true,
      group: "Classification",
      help: "Derived from HQ Sub Industry using irxdx.",
    },
    {
      key: "primaryCategory",
      header: "account_primary_category",
      label: "Primary Category",
      kind: "readonly",
      computed: true,
      group: "Classification",
      inTable: true,
      help: "Derived from HQ Sub Industry using irxdx.",
    },
    {
      key: "primaryNature",
      header: "account_primary_nature",
      label: "Primary Nature",
      kind: "readonly",
      computed: true,
      group: "Classification",
      help: "Derived from HQ Sub Industry using irxdx.",
    },
    { key: "forbes", header: "account_hq_forbes_2000_rank", label: "Forbes 2000 Rank", kind: "number", group: "Classification", help: "Blank if unranked." },
    { key: "fortune", header: "account_hq_fortune_500_rank", label: "Fortune 500 Rank", kind: "number", group: "Classification", help: "Blank if unranked." },
    {
      key: "companyType",
      header: "account_hq_company_type",
      label: "HQ Company Type",
      kind: "select",
      required: true,
      group: "Classification",
      options: [
        "Public",
        "Private",
        "Subsidiary",
        "ACQSP",
        "ACQMP",
        "Merger",
        "Bankrupt / In Liquidation",
      ],
    },

    { key: "revenue", header: "account_hq_revenue", label: "HQ Revenue (USD Mil)", kind: "number", group: "Revenue", inTable: true },
    {
      key: "revenueRange",
      header: "account_hq_revenue_range",
      label: "HQ Revenue Range",
      kind: "readonly",
      computed: true,
      group: "Revenue",
      help: "Banded from the revenue figure by the sheet. Change the revenue to move it.",
    },
    { key: "fyEnd", header: "account_hq_fy_end", label: "HQ FY End", kind: "select", group: "Revenue", options: MONTHS },
    { key: "revenueYear", header: "account_hq_revenue_year", label: "HQ Revenue Year", kind: "year", group: "Revenue" },
    { key: "revenueSourceType", header: "account_hq_revenue_source_type", label: "Revenue Source Type", kind: "select", group: "Revenue", options: SOURCE_TYPES },
    { key: "revenueSourceLink", header: "account_hq_revenue_source_link", label: "Revenue Source Link", kind: "url", group: "Revenue" },

    { key: "employees", header: "account_hq_employee_count", label: "HQ Employee Count", kind: "number", group: "Employees", inTable: true },
    {
      key: "employeeRange",
      header: "account_hq_employee_range",
      label: "HQ Employee Range",
      kind: "readonly",
      computed: true,
      group: "Employees",
      help: "Banded from the employee count by the sheet. Change the count to move it.",
    },
    { key: "employeeSourceType", header: "account_hq_employee_source_type", label: "Employee Source Type", kind: "select", required: true, group: "Employees", options: SOURCE_TYPES },
    { key: "employeeSourceLink", header: "account_hq_employee_source_link", label: "Employee Source Link", kind: "url", group: "Employees" },

    {
      key: "centerEmployees",
      header: "account_center_employees",
      label: "Center Employees (India)",
      kind: "readonly",
      computed: true,
      group: "India Footprint",
      help: "Summed from centers. Edit the centers to change it.",
    },
    {
      key: "centerEmployeesRange",
      header: "account_center_employees_range",
      label: "Center Employees Range",
      kind: "readonly",
      computed: true,
      group: "India Footprint",
      help: "Banded from the center employee total by the sheet.",
    },
    {
      key: "yearsInIndia",
      header: "years_in_india",
      label: "Years in India",
      kind: "readonly",
      computed: true,
      group: "India Footprint",
      help: "Calculated from the first center year.",
    },
    {
      key: "firstCenterYear",
      header: "account_first_center_year",
      label: "First Center Year",
      kind: "readonly",
      computed: true,
      group: "India Footprint",
      help: "Looked up from centers. Edit the centers there to change it.",
    },
    {
      key: "primaryCity",
      header: "account_primary_city",
      label: "Primary City",
      kind: "combo",
      noUrl: true,
      group: "India Footprint",
      inTable: true,
    },
    {
      key: "hubStructure",
      header: "account_hub_structure",
      label: "Hub Structure",
      kind: "select",
      group: "India Footprint",
      options: HUB_STRUCTURES,
    },
    {
      key: "visibility",
      header: "account_visibility",
      label: "Visibility",
      kind: "select",
      required: true,
      group: "India Footprint",
      inTable: true,
      options: ["GCC", "NON-GCC"],
    },
    {
      key: "visibilityNote",
      header: "account_visibility_note",
      label: "Visibility Note",
      kind: "longtext",
      noUrl: true,
      group: "India Footprint",
      help: "Only applies when Visibility is 'NON-GCC'.",
    },

    { key: "comments", header: "account_comments", label: "Comments", kind: "longtext", group: "Notes", maxLength: 2500 },
  ],
};
