import type { SheetSchema } from "./types";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
] as const;

/**
 * Canonical source-type list. The sheet also contains one-off strays
 * ("Website", "Reuters") which stay readable but are not offered as new choices.
 */
const SOURCE_TYPES = [
  "Annual Report",
  "Company Website",
  "Forbes",
  "Fortune",
  "Others",
] as const;

export const BR_SCHEMA: SheetSchema = {
  id: "br",
  sheetName: "BR",
  label: "BR",
  idHeader: "BRUID",
  idPrefix: "BR",
  titleHeader: "Account Global Legal Name",
  // One row is one company, so the legal name really must be unique.
  titleUnique: true,
  subtitleHeaders: ["HQ City", "HQ Country"],
  archiveSheetName: "BR_Archive",
  groups: [
    "Identity",
    "Company",
    "HQ Location",
    "Web & Profile",
    "Classification",
    "Revenue",
    "Employees",
    "Center Profile",
    "Notes",
  ],
  fields: [
    {
      key: "bruid",
      header: "BRUID",
      label: "BRUID",
      kind: "readonly",
      group: "Identity",
      inTable: true,
      help: "Assigned automatically on create. Never changes.",
    },
    {
      key: "date",
      header: "Date",
      label: "Date",
      kind: "date",
      required: true,
      group: "Identity",
      inTable: true,
      help: "Stored as d-MMMM-yyyy to match the existing sheet.",
    },
    {
      key: "nasscomStatus",
      header: "Nasscom Status",
      label: "Nasscom Status",
      kind: "select",
      required: true,
      options: ["Yes", "No"],
      group: "Identity",
    },
    {
      key: "nasscomMemberStatus",
      header: "Nasscom Member Status",
      label: "Nasscom Member Status",
      kind: "select",
      required: true,
      options: ["Yes", "No"],
      group: "Identity",
    },

    {
      key: "accountName",
      header: "Account Global Legal Name",
      label: "Account Global Legal Name",
      kind: "text",
      required: true,
      group: "Company",
      inTable: true,
      maxLength: 150,
      help: "Must be unique across BR.",
    },
    {
      key: "aboutCompany",
      header: "About Company",
      label: "About Company",
      kind: "longtext",
      required: true,
      group: "Company",
      maxLength: 2000,
    },

    {
      key: "hqAddress",
      header: "HQ Address",
      label: "HQ Address",
      kind: "longtext",
      required: true,
      group: "HQ Location",
      maxLength: 250,
    },
    { key: "hqCity", header: "HQ City", label: "HQ City", kind: "combo", required: true, group: "HQ Location", inTable: true },
    { key: "hqState", header: "HQ State", label: "HQ State", kind: "combo", required: true, group: "HQ Location" },
    { key: "hqZip", header: "HQZIPCode", label: "HQ ZIP Code", kind: "text", group: "HQ Location" },
    { key: "hqCountry", header: "HQ Country", label: "HQ Country", kind: "combo", required: true, group: "HQ Location", inTable: true },
    {
      key: "hqRegion",
      header: "HQ Region",
      label: "HQ Region",
      kind: "select",
      required: true,
      options: ["North America", "Europe", "APAC", "MEA", "LATAM"],
      group: "HQ Location",
    },

    { key: "hqBroadLine", header: "HQ Broad Line", label: "HQ Broad Line", kind: "text", group: "Web & Profile", help: "Main switchboard number." },
    { key: "hqWebsite", header: "HQ Website", label: "HQ Website", kind: "url", required: true, group: "Web & Profile", inTable: true },
    { key: "linkedin", header: "Linkedin Link", label: "LinkedIn Link", kind: "url", required: true, group: "Web & Profile" },
    {
      key: "hqOfferings",
      header: "HQ Offerings",
      label: "HQ Offerings",
      kind: "longtext",
      required: true,
      group: "Web & Profile",
      maxLength: 600,
      help: "One offering per line.",
    },
    { key: "offeringSourceLink", header: "Source Link\n(HQ Offering)", label: "Source Link (HQ Offering)", kind: "url", required: true, group: "Web & Profile" },

    {
      key: "hqSubIndustry",
      header: "HQ Sub Industry",
      label: "HQ Sub Industry",
      kind: "combo",
      required: true,
      group: "Classification",
      optionSource: { sheetName: "IRxDx", header: "Sub Industry" },
      help: "Choose a Sub Industry from IRxDx. The related classification fields fill automatically.",
    },
    {
      key: "hqIndustry",
      header: "HQ Industry",
      label: "HQ Industry",
      kind: "readonly",
      computed: true,
      group: "Classification",
      help: "Derived from HQ Sub Industry using IRxDx.",
    },
    {
      key: "primaryCategory",
      header: "Primary Category",
      label: "Primary Category",
      kind: "readonly",
      computed: true,
      group: "Classification",
      inTable: true,
      help: "Derived from HQ Sub Industry using IRxDx.",
    },
    {
      key: "primaryNature",
      header: "Primary Nature",
      label: "Primary Nature",
      kind: "readonly",
      computed: true,
      group: "Classification",
      help: "Derived from HQ Sub Industry using IRxDx.",
    },
    { key: "forbes", header: "HQ Forbes 2026", label: "HQ Forbes 2026", kind: "number", group: "Classification", help: "Forbes Global 2000 rank. Blank if unranked." },
    { key: "fortune", header: "HQ Fortune Rank 2026", label: "HQ Fortune Rank 2026", kind: "number", group: "Classification", help: "Fortune 500 rank. Blank if unranked." },
    {
      key: "companyType",
      header: "HQ Company Type",
      label: "HQ Company Type",
      kind: "select",
      required: true,
      group: "Classification",
      options: ["Public", "Private", "Subsidiary", "ACQSP", "ACQMP", "Merger"],
    },

    { key: "revenue", header: "HQ Revenue\n(in USD Mil)", label: "HQ Revenue (USD Mil)", kind: "number", required: true, group: "Revenue", inTable: true },
    {
      key: "revenueRange",
      header: "HQ Revenue Range",
      label: "HQ Revenue Range",
      kind: "readonly",
      computed: true,
      group: "Revenue",
      help: "Banded from the revenue figure by the sheet. Change the revenue to move it.",
    },
    { key: "fyEnd", header: "HQ FY End", label: "HQ FY End", kind: "select", group: "Revenue", options: MONTHS },
    { key: "revenueYear", header: "HQ Revenue Year", label: "HQ Revenue Year", kind: "year", group: "Revenue" },
    { key: "revenueSourceType", header: "Source Type\n(HQ Revenue)", label: "Source Type (HQ Revenue)", kind: "select", required: true, group: "Revenue", options: SOURCE_TYPES },
    { key: "revenueSourceLink", header: "Source Link\n(HQ Revenue)", label: "Source Link (HQ Revenue)", kind: "url", required: true, group: "Revenue" },

    { key: "employees", header: "HQ Employee Count", label: "HQ Employee Count", kind: "number", required: true, group: "Employees", inTable: true },
    {
      key: "employeeRange",
      header: "HQ Employee Range",
      label: "HQ Employee Range",
      kind: "readonly",
      computed: true,
      group: "Employees",
      help: "Banded from the employee count by the sheet. Change the count to move it.",
    },
    { key: "employeeSourceType", header: "Source Type\n(HQ Employee)", label: "Source Type (HQ Employee)", kind: "select", required: true, group: "Employees", options: SOURCE_TYPES },
    { key: "employeeSourceLink", header: "Source Link\n(HQ Employee)", label: "Source Link (HQ Employee)", kind: "url", required: true, group: "Employees" },

    { key: "comments", header: "Comments (CD)", label: "Comments (CD)", kind: "longtext", group: "Notes", maxLength: 2500 },

    {
      key: "firstCenter",
      header: "First Center",
      label: "First Center (Year)",
      kind: "readonly",
      computed: true,
      group: "Center Profile",
      help: "Looked up from CM. Edit the centers there to change it.",
    },
    {
      key: "centerTypePriority",
      header: "Center Type Priority",
      label: "Center Type Priority",
      kind: "readonly",
      computed: true,
      group: "Center Profile",
      inTable: true,
      help: "Looked up from CM. Edit the centers there to change it.",
    },
    {
      key: "gccStatus",
      header: "GCC/Non GCC",
      label: "GCC / Non GCC",
      kind: "select",
      required: true,
      group: "Center Profile",
      inTable: true,
      options: ["GCC", "Non GCC"],
    },
    {
      key: "nonGccComments",
      header: "Non GCC Comments",
      label: "Non GCC Comments",
      kind: "longtext",
      group: "Center Profile",
      help: "Only applies when GCC / Non GCC is 'Non GCC'.",
    },
    {
      key: "hubStructure",
      header: "Hub Structure",
      label: "Hub Structure",
      kind: "readonly",
      computed: true,
      group: "Center Profile",
      help: "Looked up from the Hub Structure sheet.",
    },
    {
      key: "primaryLocation",
      header: "Primary Location",
      label: "Primary Location",
      kind: "readonly",
      computed: true,
      group: "Center Profile",
      inTable: true,
      help: "Looked up from the Hub Structure sheet.",
    },

  ],
};
