import type { SheetSchema } from "./types";
import { MONTHS } from "./accounts";

/** Shared with services. Both sheets describe the same centers. */
export const CENTER_TYPES = [
  "BPO", "CoE", "Distribution", "Engineering & Design", "GBS",
  "GCC/GIC", "IT", "Manufacturing", "R&D", "Sales & Marketing", "SSC",
] as const;

export const CENTER_FOCUS = [
  "Both",
  "Global Support Services",
  "Local Support Services",
] as const;

const INDIAN_STATES = [
  "Andhra Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa", "Gujarat",
  "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka",
  "Kerala", "Madhya Pradesh", "Maharashtra", "Meghalaya", "Odisha",
  "Puducherry", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana",
  "Uttar Pradesh", "Uttarakhand", "West Bengal", "TBA",
] as const;

/**
 * `centers` is one row per center. Field order below is the column order in
 * the sheet, A onwards: the repo maps fields to columns by position.
 */
export const CENTERS_SCHEMA: SheetSchema = {
  id: "centers",
  sheetName: "centers",
  label: "Centers",
  idHeader: "uuid",
  // The sheet's own ids read CN2, CN3...
  idPrefix: "CN",
  titleHeader: "center_name",
  // One company runs many centers, so center names legitimately repeat.
  titleUnique: false,
  subtitleHeaders: ["account_global_legal_name", "center_city"],
  archiveSheetName: "centers_archive",
  groups: [
    "Identity",
    "Company & Center",
    "Timeline",
    "Ownership",
    "Classification",
    "Contact & Sources",
    "Location",
    "Headcount",
    "Derived",
    "Notes",
  ],
  fields: [
    {
      key: "uuid",
      header: "uuid",
      label: "UUID",
      kind: "readonly",
      group: "Identity",
      inTable: true,
      help: "Assigned automatically on create. Never changes.",
    },
    {
      key: "lastUpdateDate",
      header: "last_update_date",
      label: "Last Update Date",
      kind: "date",
      required: true,
      group: "Identity",
      help: "Stored as d-MMMM-yyyy to match the existing sheet.",
    },
    {
      key: "cnUniqueMerge",
      header: "cn_unique_merge",
      label: "CN Unique Merge",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "Built by the sheet from account, center, type, focus and city.",
    },
    {
      key: "cnUniqueKey",
      header: "cn_unique_key",
      label: "CN Unique Key",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "The sheet's own duplicate check. Calculated, not editable.",
    },

    {
      key: "accountName",
      header: "account_global_legal_name",
      label: "Account Global Legal Name",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Company & Center",
      inTable: true,
      // Chosen from accounts rather than typed, so the value is copied byte for
      // byte and the lookups between the registers cannot drift on casing or spacing.
      optionSource: { sheetName: "accounts", header: "account_global_legal_name" },
      help: "Choose the account from accounts. Add the account there first if it is missing.",
    },
    {
      key: "centerLegalName",
      header: "center_name",
      label: "Center Name",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Company & Center",
      inTable: true,
      maxLength: 120,
      optionSource: {
        sheetName: "centers",
        header: "center_name",
        groupBy: { header: "account_global_legal_name", fieldKey: "accountName" },
        creatable: true,
      },
      help: "Pick one of the account's existing centers, or add a new name. Services copies it exactly.",
    },
    {
      key: "centerStatus",
      header: "center_status",
      label: "Center Status",
      kind: "select",
      required: true,
      group: "Company & Center",
      inTable: true,
      options: ["Active Center", "Upcoming", "Non Operational"],
    },

    {
      key: "incYear",
      header: "center_inc_year",
      label: "Incorporation Year",
      kind: "year",
      group: "Timeline",
      help: "Year this center opened.",
    },
    {
      key: "announcedYear",
      header: "announced_year",
      label: "Announced Year",
      kind: "year",
      group: "Timeline",
      help: "Only for centers announced but not yet open.",
    },
    {
      key: "announcedMonth",
      header: "announced_month",
      label: "Announced Month",
      kind: "select",
      group: "Timeline",
      options: MONTHS,
    },
    {
      key: "incYearNotes",
      header: "center_inc_year_notes",
      label: "Incorporation Year Notes",
      kind: "longtext",
      group: "Timeline",
      maxLength: 500,
    },
    {
      key: "incYearLink",
      header: "center_inc_year_updated_link",
      label: "Incorporation Year Source",
      kind: "url",
      group: "Timeline",
    },
    {
      key: "timeline",
      header: "center_timeline",
      label: "Timeline",
      kind: "readonly",
      computed: true,
      group: "Timeline",
      help: "Banded from the incorporation or announced year by the sheet.",
    },
    {
      key: "endYear",
      header: "center_end_year",
      label: "End Year",
      kind: "year",
      group: "Timeline",
      help: "Only for centers that have closed.",
    },

    {
      key: "managementPartner",
      header: "center_management_partner",
      label: "Center Management Partner",
      kind: "text",
      noUrl: true,
      group: "Ownership",
      maxLength: 120,
    },
    {
      key: "jvStatus",
      header: "center_jv_status",
      label: "JV Status",
      kind: "select",
      group: "Ownership",
      options: ["JV", "Partnership"],
    },
    {
      key: "jvName",
      header: "center_jv_name",
      label: "JV Name",
      kind: "text",
      noUrl: true,
      group: "Ownership",
      maxLength: 150,
    },

    {
      key: "centerType",
      header: "center_type",
      label: "Center Type",
      kind: "select",
      required: true,
      group: "Classification",
      inTable: true,
      options: CENTER_TYPES,
    },
    {
      key: "centerFocus",
      header: "center_focus",
      label: "Center Focus",
      kind: "select",
      required: true,
      group: "Classification",
      options: CENTER_FOCUS,
    },

    {
      key: "centerSourceLink",
      header: "center_source_link",
      label: "Center Source Link",
      kind: "url",
      required: true,
      group: "Contact & Sources",
      help: "One link per line.",
    },
    {
      key: "accountWebsite",
      header: "center_account_website",
      label: "Account Website",
      kind: "readonly",
      computed: true,
      group: "Contact & Sources",
      help: "Looked up from accounts.",
    },
    {
      key: "centerWebsite",
      header: "center_website",
      label: "Center Website",
      kind: "url",
      group: "Contact & Sources",
    },
    {
      key: "centerLinkedin",
      header: "center_linkedin",
      label: "Center LinkedIn Page",
      kind: "url",
      format: "linkedin",
      group: "Contact & Sources",
    },

    {
      key: "address",
      header: "center_address",
      label: "Address",
      kind: "longtext",
      noUrl: true,
      group: "Location",
      maxLength: 300,
    },
    {
      key: "microLocation",
      header: "center_micro_location",
      label: "Micro Location",
      kind: "readonly",
      computed: true,
      group: "Location",
      help: "Looked up from the micro-location sheet, which the team maintains by hand.",
    },
    {
      key: "city",
      header: "center_city",
      label: "City",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Location",
      inTable: true,
    },
    {
      key: "state",
      header: "center_state",
      label: "State",
      kind: "select",
      required: true,
      group: "Location",
      options: INDIAN_STATES,
    },
    {
      key: "zipCode",
      header: "center_zip_code",
      label: "Zip Code",
      kind: "text",
      format: "pincode6",
      noUrl: true,
      group: "Location",
    },
    {
      key: "country",
      header: "center_country",
      label: "Country",
      kind: "select",
      required: true,
      group: "Location",
      options: ["India"],
    },
    {
      key: "countryIso2",
      header: "center_country_iso2",
      label: "Country ISO2",
      kind: "select",
      required: true,
      group: "Location",
      options: ["IN"],
    },
    {
      key: "lat",
      header: "lat",
      label: "Latitude",
      kind: "readonly",
      computed: true,
      spill: true,
      group: "Location",
      help: "Filled by the co-ordinates lookup in the sheet from city, state and country.",
    },
    {
      key: "lng",
      header: "lng",
      label: "Longitude",
      kind: "readonly",
      computed: true,
      spill: true,
      group: "Location",
      help: "Filled by the co-ordinates lookup in the sheet from city, state and country.",
    },
    {
      key: "boardline",
      header: "center_boardline",
      label: "Boardline Number",
      kind: "text",
      format: "digits",
      noUrl: true,
      group: "Contact & Sources",
    },

    {
      key: "employeeCountArticle",
      header: "center_employees_article",
      label: "Employee Count (Article)",
      kind: "number",
      group: "Headcount",
    },
    {
      key: "employeeArticleLink",
      header: "center_employees_article_source_link",
      label: "Employee Source (Article)",
      kind: "url",
      group: "Headcount",
    },
    {
      key: "employeeCountLinkedin",
      header: "center_employees_linkedin",
      label: "Employee Count (LinkedIn)",
      kind: "number",
      group: "Headcount",
      inTable: true,
    },
    {
      key: "employeeLinkedinLink",
      header: "center_employees_range_linkedin_source_link",
      label: "Employee Source (LinkedIn)",
      kind: "url",
      group: "Headcount",
    },
    {
      key: "employees",
      header: "center_employees",
      label: "Employees",
      kind: "readonly",
      computed: true,
      group: "Headcount",
      help: "The lower of the article and LinkedIn counts. Calculated by the sheet.",
    },
    {
      key: "employeesRange",
      header: "center_employees_range",
      label: "Employees Range",
      kind: "readonly",
      computed: true,
      group: "Headcount",
      help: "Banded from the employee figure by the sheet.",
    },

    {
      key: "services",
      header: "center_services",
      label: "Services",
      kind: "readonly",
      computed: true,
      spill: true,
      group: "Derived",
      help: "Summarised from the services register by the sheet.",
    },
    {
      key: "firstYear",
      header: "center_first_year",
      label: "First Center Year",
      kind: "readonly",
      computed: true,
      group: "Derived",
      help: "Earliest qualifying center for this account. Calculated by the sheet.",
    },

    {
      key: "employeesComment",
      header: "center_employees_comment",
      label: "Employees Comment",
      kind: "longtext",
      group: "Notes",
      maxLength: 2000,
    },
    {
      key: "centerComments",
      header: "center_comments",
      label: "Center Comments",
      kind: "longtext",
      group: "Notes",
      maxLength: 6500,
    },
  ],
};
