import type { SheetSchema } from "./types";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
] as const;

/** Shared with SM. Both sheets describe the same centers. */
export const CENTER_TYPES = [
  "BPO", "CoE", "Distribution", "Engineering & Design", "GBS",
  "GCC/GIC", "IT", "Manufacturing", "R&D", "Sales & Marketing", "SSC",
] as const;

export const CENTER_FOCUS = [
  "Both",
  "Global Support Services",
  "Local Support Services",
] as const;

const INDIAN_STATES = [
  "Andhra Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa", "Gujarat",
  "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka",
  "Kerala", "Madhya Pradesh", "Maharashtra", "Meghalaya", "Odisha",
  "Puducherry", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana",
  "Uttar Pradesh", "Uttarakhand", "West Bengal", "TBA",
] as const;

export const CM_SCHEMA: SheetSchema = {
  id: "cm",
  sheetName: "CM",
  label: "CM",
  idHeader: "UUID",
  // The sheet's own ids read CN2, CN3... even though the tab is called CM.
  idPrefix: "CN",
  titleHeader: "Center Legal Name",
  // One company runs many centers, so center names legitimately repeat.
  titleUnique: false,
  subtitleHeaders: ["Account Global Legal Name", "City"],
  archiveSheetName: "CM_Archive",
  groups: [
    "Identity",
    "Company & Center",
    "Timeline",
    "Ownership",
    "Classification",
    "Location",
    "Contact & Sources",
    "Headcount",
    "Updates",
    "Notes",
  ],
  fields: [
    {
      key: "uuid",
      header: "UUID",
      label: "UUID",
      kind: "readonly",
      group: "Identity",
      inTable: true,
      help: "Assigned automatically on create. Never changes.",
    },
    {
      key: "lastUpdateDate",
      header: "Last Update Date",
      label: "Last Update Date",
      kind: "date",
      required: true,
      group: "Identity",
      help: "Stored as d-MMMM-yyyy to match the existing sheet.",
    },
    {
      key: "cnConcatenate",
      header: "CN CONCATENATE",
      label: "CN Concatenate",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "Built by the sheet from company, center, type, focus and city.",
    },
    {
      key: "cnUniqueKey",
      header: "CN Unique Key",
      label: "CN Unique Key",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "The sheet's own duplicate check. Calculated, not editable.",
    },

    {
      key: "accountName",
      header: "Account Global Legal Name",
      label: "Account Global Legal Name",
      kind: "combo",
      required: true,
      group: "Company & Center",
      inTable: true,
      // Chosen from BR rather than typed, so the value is copied byte for byte
      // and the lookups between the registers cannot drift on casing or spacing.
      optionSource: { sheetName: "BR", header: "Account Global Legal Name" },
      help: "Choose the account from BR. Add the account there first if it is missing.",
    },
    {
      key: "centerLegalName",
      header: "Center Legal Name",
      label: "Center Legal Name",
      kind: "combo",
      required: true,
      group: "Company & Center",
      inTable: true,
      maxLength: 120,
      optionSource: {
        sheetName: "CM",
        header: "Center Legal Name",
        groupBy: { header: "Account Global Legal Name", fieldKey: "accountName" },
        creatable: true,
      },
      help: "Pick one of the account's existing centers, or add a new name. SM copies it exactly.",
    },
    {
      key: "centerStatus",
      header: "Center Status",
      label: "Center Status",
      kind: "select",
      required: true,
      group: "Company & Center",
      inTable: true,
      options: ["Active Center", "Upcoming", "Non Operational"],
    },

    {
      key: "incYear",
      header: "Inc Year",
      label: "Incorporation Year",
      kind: "year",
      group: "Timeline",
      help: "Year this center opened.",
    },
    {
      key: "announcedYear",
      header: "Announced Year",
      label: "Announced Year",
      kind: "year",
      group: "Timeline",
      help: "Only for centers announced but not yet open.",
    },
    {
      key: "month",
      header: "Month",
      label: "Month",
      kind: "select",
      group: "Timeline",
      options: MONTHS,
    },
    {
      key: "incYearNotes",
      header: "Inc Year Notes",
      label: "Incorporation Year Notes",
      kind: "longtext",
      group: "Timeline",
      maxLength: 500,
    },
    {
      key: "incYearLink",
      header: "Updated Inc Year Link",
      label: "Incorporation Year Source",
      kind: "url",
      group: "Timeline",
    },
    {
      key: "timeLine",
      header: "Time Line",
      label: "Time Line",
      kind: "text",
      group: "Timeline",
      help: "Free text, e.g. 2016 - 2020.",
    },
    {
      key: "endYear",
      header: "End Year",
      label: "End Year",
      kind: "year",
      group: "Timeline",
      help: "Only for centers that have closed.",
    },

    {
      key: "managementPartner",
      header: "Center Management Partner",
      label: "Center Management Partner",
      kind: "text",
      group: "Ownership",
      maxLength: 120,
    },
    {
      key: "jvStatus",
      header: "JV Status",
      label: "JV Status",
      kind: "select",
      group: "Ownership",
      options: ["JV", "Partnership"],
    },
    {
      key: "jvName",
      header: "JV Name",
      label: "JV Name",
      kind: "text",
      group: "Ownership",
      maxLength: 150,
    },

    {
      key: "centerType",
      header: "Center Type",
      label: "Center Type",
      kind: "select",
      required: true,
      group: "Classification",
      inTable: true,
      options: CENTER_TYPES,
    },
    {
      // The sheet's header is misspelled. It has to match character for
      // character, so the typo stays in `header` and is fixed in `label`.
      key: "centerFocus",
      header: "Center Foucs",
      label: "Center Focus",
      kind: "select",
      required: true,
      group: "Classification",
      options: CENTER_FOCUS,
    },

    {
      key: "centerSourceLink",
      header: "Center Souce Link",
      label: "Center Source Link",
      kind: "url",
      required: true,
      group: "Contact & Sources",
      help: "One link per line.",
    },
    {
      key: "centerWebsite",
      header: "Center Website",
      label: "Center Website",
      kind: "url",
      group: "Contact & Sources",
    },
    {
      key: "centerLinkedin",
      header: "Center Linkedin Page",
      label: "Center LinkedIn Page",
      kind: "url",
      group: "Contact & Sources",
    },

    {
      key: "address",
      header: "Address",
      label: "Address",
      kind: "longtext",
      required: true,
      group: "Location",
      maxLength: 300,
    },
    {
      key: "microlocation",
      header: "Microlocation",
      label: "Microlocation",
      kind: "readonly",
      computed: true,
      group: "Location",
      help: "Looked up from the Microlocations sheet, which the team maintains by hand.",
    },
    {
      key: "city",
      header: "City",
      label: "City",
      kind: "combo",
      required: true,
      group: "Location",
      inTable: true,
    },
    {
      key: "state",
      header: "State",
      label: "State",
      kind: "select",
      required: true,
      group: "Location",
      options: INDIAN_STATES,
    },
    {
      key: "zipCode",
      header: "Zip Code",
      label: "Zip Code",
      kind: "text",
      group: "Location",
    },
    {
      key: "country",
      header: "Country",
      label: "Country",
      kind: "select",
      required: true,
      group: "Location",
      options: ["India"],
    },

    {
      key: "broadlineNumber",
      header: "Broadline Number",
      label: "Broadline Number",
      kind: "text",
      group: "Contact & Sources",
    },

    {
      key: "employeeCountArticle",
      header: "Employee Count\nArticle",
      label: "Employee Count (Article)",
      kind: "number",
      group: "Headcount",
    },
    {
      key: "employeeArticleLink",
      header: "Employee Source\n(Article) Link",
      label: "Employee Source (Article)",
      kind: "url",
      group: "Headcount",
    },
    {
      key: "employeeCountLinkedin",
      header: "Employees Count\nLinkedin ( June 2026 )",
      label: "Employee Count (LinkedIn)",
      kind: "number",
      group: "Headcount",
      inTable: true,
    },
    {
      key: "employeeLinkedinLink",
      header: "Employees Count\n(Linkedin) Link",
      label: "Employee Source (LinkedIn)",
      kind: "url",
      group: "Headcount",
    },

    {
      key: "updates",
      header: "Updates",
      label: "Update Type",
      kind: "select",
      group: "Updates",
      options: [
        "Center Expansion",
        "Employees Expansion",
        "Hiring",
        "Layoff",
        "Services added to existing center",
        "Non-operational",
        "Partnered for Growth",
        "Acquired Another company for growth",
      ],
    },
    {
      key: "updateBrief",
      header: "Update Brief",
      label: "Update Brief",
      kind: "longtext",
      group: "Updates",
      maxLength: 500,
    },
    {
      key: "updateDate",
      header: "Update Date",
      label: "Update Date",
      kind: "date",
      group: "Updates",
      help: "Stored as d-MMMM-yyyy, e.g. 7-August-2026.",
    },
    {
      key: "updateLink",
      header: "Update Link",
      label: "Update Link",
      kind: "url",
      group: "Updates",
    },

    {
      key: "employeesComment",
      header: "Employees Comment",
      label: "Employees Comment",
      kind: "longtext",
      group: "Notes",
      maxLength: 2000,
    },
    {
      key: "centerComments",
      header: "Center Comments",
      label: "Center Comments",
      kind: "longtext",
      group: "Notes",
      maxLength: 6500,
    },

    {
      key: "firstCenter",
      header: "First Center",
      label: "First Center (Year)",
      kind: "readonly",
      computed: true,
      group: "Classification",
      help: "Earliest qualifying center for this company. Calculated by the sheet.",
    },
    {
      key: "centerTypePriority",
      header: "Center Type Priority",
      label: "Center Type Priority",
      kind: "readonly",
      computed: true,
      group: "Classification",
      help: "Ranked from the company's center types. Calculated by the sheet.",
    },
  ],
};
