import type { SheetSchema } from "./types";
import { CENTER_FOCUS, CENTER_TYPES } from "./centers";

/**
 * `services` is one row per center, describing the service lines that center
 * runs. Most of it is paired columns: a free-text list of services, and the
 * links that evidence them. Field order below is the column order in the
 * sheet, A onwards: the repo maps fields to columns by position.
 */
export const SERVICES_SCHEMA: SheetSchema = {
  id: "services",
  sheetName: "services",
  label: "Services",
  idHeader: "uuid",
  idPrefix: "CN",
  titleHeader: "center_name",
  titleUnique: false,
  subtitleHeaders: ["account_global_legal_name", "center_city"],
  archiveSheetName: "services_archive",
  groups: [
    "Identity",
    "Center",
    "Focus",
    "Service Lines",
    "Software",
    "Notes",
  ],
  fields: [
    {
      key: "uuid",
      header: "uuid",
      label: "UUID",
      kind: "readonly",
      group: "Identity",
      inTable: true,
      help: "Assigned automatically on create. Never changes.",
    },
    {
      key: "lastUpdateDate",
      header: "last_update_date",
      label: "Last Update Date",
      kind: "date",
      required: true,
      group: "Identity",
      help: "Stored as d-MMMM-yyyy to match the existing sheet.",
    },
    {
      key: "cnUniqueMerge",
      header: "cn_unique_merge",
      label: "CN Unique Merge",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "Built by the sheet from account, center, type, focus and city.",
    },
    {
      key: "cnUniqueKey",
      header: "cn_unique_key",
      label: "CN Unique Key",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "The sheet's own duplicate check. Calculated, not editable.",
    },

    {
      key: "accountName",
      header: "account_global_legal_name",
      label: "Account Global Legal Name",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Center",
      inTable: true,
      optionSource: { sheetName: "accounts", header: "account_global_legal_name" },
      help: "Choose the account from accounts.",
    },
    {
      key: "centerLegalName",
      header: "center_name",
      label: "Center Name",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Center",
      inTable: true,
      maxLength: 120,
      optionSource: {
        sheetName: "centers",
        header: "center_name",
        groupBy: { header: "account_global_legal_name", fieldKey: "accountName" },
        creatable: true,
      },
      help: "Pick one of the account's centers from centers, or add a new name. It must match centers exactly.",
    },
    {
      key: "centerType",
      header: "center_type",
      label: "Center Type",
      kind: "select",
      required: true,
      group: "Center",
      inTable: true,
      options: CENTER_TYPES,
    },
    {
      key: "centerFocus",
      header: "center_focus",
      label: "Center Focus",
      kind: "select",
      required: true,
      group: "Center",
      options: CENTER_FOCUS,
    },
    {
      key: "city",
      header: "center_city",
      label: "City",
      kind: "combo",
      required: true,
      noUrl: true,
      group: "Center",
      inTable: true,
    },

    {
      key: "primaryService",
      header: "primary_service",
      label: "Primary Service",
      kind: "longtext",
      noUrl: true,
      group: "Focus",
      maxLength: 800,
      help: "One service per line.",
    },
    {
      key: "primaryServiceSource",
      header: "primary_service_source_link",
      label: "Primary Service Source",
      kind: "url",
      group: "Focus",
    },
    {
      key: "focusRegion",
      header: "focus_region",
      label: "Focus Region",
      kind: "longtext",
      noUrl: true,
      group: "Focus",
      maxLength: 200,
      help: "One region per line, e.g. Global, India, LATM.",
    },
    {
      key: "focusRegionSource",
      header: "focus_region_link",
      label: "Focus Region Source",
      kind: "url",
      group: "Focus",
    },

    {
      key: "it",
      header: "service_it",
      label: "IT",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 600,
      help: "One service per line.",
    },
    { key: "itSource", header: "service_it_link", label: "IT Source", kind: "url", group: "Service Lines" },

    {
      key: "erd",
      header: "service_erd",
      label: "ER&D",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 600,
    },
    { key: "erdSource", header: "service_erd_link", label: "ER&D Source", kind: "url", group: "Service Lines" },

    {
      key: "fna",
      header: "service_fna",
      label: "Finance & Accounting",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 600,
    },
    { key: "fnaSource", header: "service_fna_link", label: "Finance & Accounting Source", kind: "url", group: "Service Lines" },

    {
      key: "hr",
      header: "service_hr",
      label: "HR",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 600,
    },
    { key: "hrSource", header: "service_hr_link", label: "HR Source", kind: "url", group: "Service Lines" },

    {
      key: "procurement",
      header: "service_procurement",
      label: "Procurement & Supply Chain",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 600,
    },
    {
      key: "procurementSource",
      header: "service_procurement_link",
      label: "Procurement & Supply Chain Source",
      kind: "url",
      group: "Service Lines",
    },

    {
      key: "salesMarketing",
      header: "service_sales_marketing",
      label: "Sales & Marketing",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 700,
    },
    {
      key: "salesMarketingSource",
      header: "service_sales_marketing_link",
      label: "Sales & Marketing Source",
      kind: "url",
      group: "Service Lines",
    },

    {
      key: "customerSupport",
      header: "service_customer_support",
      label: "Customer Support Services",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 400,
    },
    {
      key: "customerSupportSource",
      header: "service_customer_support_link",
      label: "Customer Support Source",
      kind: "url",
      group: "Service Lines",
    },

    {
      key: "others",
      header: "service_others",
      label: "Other Services",
      kind: "longtext",
      noUrl: true,
      group: "Service Lines",
      maxLength: 800,
    },
    { key: "othersSource", header: "service_others_link", label: "Other Services Source", kind: "url", group: "Service Lines" },

    {
      key: "softwareVendor",
      header: "software_vendor",
      label: "Software Vendor",
      kind: "longtext",
      noUrl: true,
      group: "Software",
      maxLength: 500,
      help: "One vendor per line.",
    },
    {
      key: "softwareInUse",
      header: "software_in_use",
      label: "Software in Use",
      kind: "longtext",
      noUrl: true,
      group: "Software",
      maxLength: 400,
    },
    {
      key: "softwareSource",
      header: "software_in_use_link",
      label: "Software Source",
      kind: "url",
      group: "Software",
    },

    {
      key: "comments",
      header: "comments",
      label: "Comments",
      kind: "longtext",
      group: "Notes",
      maxLength: 1500,
    },
  ],
};
