import type { SheetSchema } from "./types";
import { CENTER_FOCUS, CENTER_TYPES } from "./cm";

const TEAM_MEMBERS = [
  "Anusha", "Ayushi", "Pradhyumna", "Priyansh", "Rakshan",
  "Ranu", "Renuka", "Sangeeta", "Shreya", "Surabhi",
] as const;

/**
 * SM is one row per center, describing the service lines that center runs.
 * Most of it is paired columns: a free-text list of services, and the links
 * that evidence them.
 */
export const SM_SCHEMA: SheetSchema = {
  id: "sm",
  sheetName: "SM",
  label: "SM",
  idHeader: "UUID",
  idPrefix: "CN",
  titleHeader: "Center Legal Name",
  titleUnique: false,
  subtitleHeaders: ["Account Global Legal Name", "City"],
  archiveSheetName: "SM_Archive",
  groups: [
    "Identity",
    "Center",
    "Focus",
    "Service Lines",
    "Software",
    "Notes",
  ],
  fields: [
    {
      key: "uuid",
      header: "UUID",
      label: "UUID",
      kind: "readonly",
      group: "Identity",
      inTable: true,
      help: "Assigned automatically on create. Never changes.",
    },
    {
      key: "lastUpdateDate",
      header: "Last Update Date",
      label: "Last Update Date",
      kind: "date",
      required: true,
      group: "Identity",
      help: "Stored as d-MMMM-yyyy to match the existing sheet.",
    },
    {
      key: "teamMember",
      header: "Team Member",
      label: "Team Member",
      kind: "select",
      required: true,
      group: "Identity",
      options: TEAM_MEMBERS,
      help: "Who researched this row.",
    },
    {
      key: "cnConcatenate",
      header: "CN CONCATENATE",
      label: "CN Concatenate",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "Built by the sheet from company, center, type, focus and city.",
    },
    {
      key: "cnUniqueKey",
      header: "CN Unique Key",
      label: "CN Unique Key",
      kind: "readonly",
      computed: true,
      group: "Identity",
      help: "The sheet's own duplicate check. Calculated, not editable.",
    },

    {
      key: "accountName",
      header: "Account Global Legal Name",
      label: "Account Global Legal Name",
      kind: "combo",
      required: true,
      group: "Center",
      inTable: true,
      optionSource: { sheetName: "BR", header: "Account Global Legal Name" },
      help: "Choose the account from BR.",
    },
    {
      key: "centerLegalName",
      header: "Center Legal Name",
      label: "Center Legal Name",
      kind: "combo",
      required: true,
      group: "Center",
      inTable: true,
      maxLength: 120,
      optionSource: {
        sheetName: "CM",
        header: "Center Legal Name",
        groupBy: { header: "Account Global Legal Name", fieldKey: "accountName" },
        creatable: true,
      },
      help: "Pick one of the account's centers from CM, or add a new name. It must match CM exactly.",
    },
    {
      key: "centerType",
      header: "Center Type",
      label: "Center Type",
      kind: "select",
      required: true,
      group: "Center",
      inTable: true,
      options: CENTER_TYPES,
    },
    {
      key: "centerFocus",
      header: "Center Focus",
      label: "Center Focus",
      kind: "select",
      required: true,
      group: "Center",
      options: CENTER_FOCUS,
    },
    {
      key: "city",
      header: "City",
      label: "City",
      kind: "combo",
      required: true,
      group: "Center",
      inTable: true,
    },

    {
      // Misspelled in the sheet; the header must match it exactly.
      key: "primaryServicesFocus",
      header: "Primary Serivces Foucs",
      label: "Primary Services Focus",
      kind: "longtext",
      group: "Focus",
      maxLength: 800,
      help: "One service per line.",
    },
    {
      key: "primaryServicesSource",
      header: "Primary Services Source",
      label: "Primary Services Source",
      kind: "url",
      group: "Focus",
    },
    {
      key: "focusRegion",
      header: "Focus Region",
      label: "Focus Region",
      kind: "longtext",
      required: true,
      group: "Focus",
      maxLength: 200,
      help: "One region per line, e.g. Global, India, LATM.",
    },
    {
      key: "focusRegionSource",
      header: "Focus Region Source Link",
      label: "Focus Region Source",
      kind: "url",
      group: "Focus",
    },

    {
      key: "it",
      header: "IT",
      label: "IT",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 600,
      help: "One service per line.",
    },
    { key: "itSource", header: "IT Source Link", label: "IT Source", kind: "url", group: "Service Lines" },

    {
      key: "erd",
      header: "ER&D",
      label: "ER&D",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 600,
    },
    { key: "erdSource", header: "ER&D Source Link", label: "ER&D Source", kind: "url", group: "Service Lines" },

    {
      key: "fna",
      header: "FnA",
      label: "Finance & Accounting",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 600,
    },
    { key: "fnaSource", header: "FnA Source Link", label: "Finance & Accounting Source", kind: "url", group: "Service Lines" },

    {
      key: "hr",
      header: "HR",
      label: "HR",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 600,
    },
    { key: "hrSource", header: "HR Source Link", label: "HR Source", kind: "url", group: "Service Lines" },

    {
      key: "procurement",
      header: "Procurement & Supply Chain",
      label: "Procurement & Supply Chain",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 600,
    },
    {
      key: "procurementSource",
      header: "Procurement & Supply Chain Source Link",
      label: "Procurement & Supply Chain Source",
      kind: "url",
      group: "Service Lines",
    },

    {
      key: "salesMarketing",
      header: "Sales & Marketing",
      label: "Sales & Marketing",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 700,
    },
    {
      key: "salesMarketingSource",
      header: "Sales & Marketing Source Link",
      label: "Sales & Marketing Source",
      kind: "url",
      group: "Service Lines",
    },

    {
      key: "customerSupport",
      header: "Customer Support Services",
      label: "Customer Support Services",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 400,
    },
    {
      key: "customerSupportSource",
      header: "Customer Services Source Link",
      label: "Customer Support Source",
      kind: "url",
      group: "Service Lines",
    },

    {
      key: "others",
      header: "Others",
      label: "Other Services",
      kind: "longtext",
      group: "Service Lines",
      maxLength: 800,
    },
    { key: "othersSource", header: "Others Source Link", label: "Other Services Source", kind: "url", group: "Service Lines" },

    {
      key: "softwareVendor",
      header: "Software Vendor",
      label: "Software Vendor",
      kind: "longtext",
      group: "Software",
      maxLength: 500,
      help: "One vendor per line.",
    },
    {
      key: "softwareInUse",
      header: "Software in Use",
      label: "Software in Use",
      kind: "longtext",
      group: "Software",
      maxLength: 400,
    },
    {
      key: "softwareSource",
      header: "Software Source Link",
      label: "Software Source",
      kind: "url",
      group: "Software",
    },

    {
      key: "comments",
      header: "Comments",
      label: "Comments",
      kind: "longtext",
      group: "Notes",
      maxLength: 1500,
    },
  ],
};
